# -*- coding: utf-8 -*-

"""Constants for Interior Finish Takeoff data records.

Keep this module independent from Revit API and existing QC Toolkit modules.
"""


SCHEMA_VERSION = "0.1.0"

UNIT_AREA_M2 = "m2"
UNIT_LENGTH_M = "m"

SOURCE_TYPE_PAINT = "PAINT"
SOURCE_TYPE_TYPE_MATERIAL = "TYPE_MATERIAL"
SOURCE_TYPE_PART_MATERIAL = "PART_MATERIAL"

VALID_SOURCE_TYPES = (
    SOURCE_TYPE_PAINT,
    SOURCE_TYPE_TYPE_MATERIAL,
    SOURCE_TYPE_PART_MATERIAL
)

RECORD_TYPE_RAW_MATERIAL = "RawMaterialRecord"
RECORD_TYPE_ROOM_MAPPING = "RoomMappingRecord"
RECORD_TYPE_INTERIOR_RULE = "InteriorRuleRecord"
RECORD_TYPE_TAKEOFF_RESULT = "TakeoffResultRecord"
RECORD_TYPE_BASEBOARD_RESULT = "BaseboardResultRecord"
RECORD_TYPE_QC_FLAG = "QCFlag"

TARGET_WALL = "WALL"
TARGET_FLOOR = "FLOOR"
TARGET_CEILING = "CEILING"
TARGET_PART = "PART"
TARGET_BASEBOARD = "BASEBOARD"

VALID_TARGET_TYPES = (
    TARGET_WALL,
    TARGET_FLOOR,
    TARGET_CEILING,
    TARGET_PART,
    TARGET_BASEBOARD
)

SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_ERROR = "ERROR"

VALID_SEVERITIES = (
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_ERROR
)
